### ISSUE TITLE
polypad-v1.9.js is compressed 

### ISSUE THREAD

**Issue by MengZhaoFly** [mathigon/polypad#1]
Awesome project, polypad-v1.9.js  is compressed, I want to learn the source code, can you give me some guidance。

**Comment by plegner** [comment]
Unfortunately, the code for Polypad is not currently open-source

**Comment by MengZhaoFly** [comment]
Unfortunately, I mainly want to learn how to achieve polygon adsorption.
What I can think of now is that it can be divided into point to edge and edge to edge adsorption, but there is no specific implementation idea.
Is there any method exposure in euclid.js or fermat.js?
Your dragging is the best I've ever seen.
